// Generated by https://quicktype.io

export interface RepositoriesResponse {
    id:                          number;
    name:                        string;
    full_name:                   string;
    html_url:                    string;
    description:                 null | string;
    url:                         string;
    language:                    null | string;    
    license:                     License | null;
}

export interface License {
    key:     string;
    name:    string;
    spdx_id: string;
    url:     string;
    node_id: string;
}
